# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, upload_to='perfiles'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intereses',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
