# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 01:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos grupos'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
