# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 07:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('aceptada', models.BooleanField(default=False)),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_enviada', to=settings.AUTH_USER_MODEL)),
                ('para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_recibida', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
